// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrify.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrify.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402211857_AddMigrationOptions")]
    partial class AddMigrationOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Migrify.Core.Entities.DiscoveredMailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Side");

                    b.ToTable("DiscoveredMailboxes");
                });

            modelBuilder.Entity("Migrify.Core.Entities.FolderMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DestinationFolderDisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DestinationFolderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MigrationJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceFolderName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId", "SourceFolderName")
                        .IsUnique();

                    b.ToTable("FolderMappings");
                });

            modelBuilder.Entity("Migrify.Core.Entities.GoogleWorkspaceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EncryptedPrivateKey")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("ImpersonationEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceAccountEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TokenUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("GoogleWorkspaceSettings");
                });

            modelBuilder.Entity("Migrify.Core.Entities.ImapProviderPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Encryption")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Pattern", "MatchType")
                        .IsUnique();

                    b.ToTable("ImapProviderPresets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e629e54-58f8-4e77-9b38-ec0012d7e3f9"),
                            Encryption = "SSL",
                            Host = "imap.gmail.com",
                            MatchType = "Domain",
                            Pattern = "gmail.com",
                            Port = 993,
                            ProviderName = "Gmail"
                        },
                        new
                        {
                            Id = new Guid("c71f0920-cce8-930f-b4e5-0ecfc71aab0e"),
                            Encryption = "SSL",
                            Host = "imap.gmail.com",
                            MatchType = "Domain",
                            Pattern = "googlemail.com",
                            Port = 993,
                            ProviderName = "Gmail"
                        },
                        new
                        {
                            Id = new Guid("c09cd863-0832-b11a-4f90-167bbec450d5"),
                            Encryption = "SSL",
                            Host = "outlook.office365.com",
                            MatchType = "Domain",
                            Pattern = "outlook.com",
                            Port = 993,
                            ProviderName = "Outlook.com"
                        },
                        new
                        {
                            Id = new Guid("048a30ce-e61a-d0cc-e52a-5f9f3cdb543b"),
                            Encryption = "SSL",
                            Host = "outlook.office365.com",
                            MatchType = "Domain",
                            Pattern = "hotmail.com",
                            Port = 993,
                            ProviderName = "Outlook.com"
                        },
                        new
                        {
                            Id = new Guid("6b17e395-e71d-2963-5d88-719de03e9014"),
                            Encryption = "SSL",
                            Host = "outlook.office365.com",
                            MatchType = "Domain",
                            Pattern = "live.com",
                            Port = 993,
                            ProviderName = "Outlook.com"
                        },
                        new
                        {
                            Id = new Guid("6d86e923-9c4e-ffda-55a3-689c1973eff2"),
                            Encryption = "SSL",
                            Host = "outlook.office365.com",
                            MatchType = "Domain",
                            Pattern = "msn.com",
                            Port = 993,
                            ProviderName = "Outlook.com"
                        },
                        new
                        {
                            Id = new Guid("335bface-248c-0a5c-62cf-96adf66ad1a6"),
                            Encryption = "SSL",
                            Host = "imap.mail.yahoo.com",
                            MatchType = "Domain",
                            Pattern = "yahoo.com",
                            Port = 993,
                            ProviderName = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("acb15a15-c727-97a4-e981-1d73c7038b9d"),
                            Encryption = "SSL",
                            Host = "imap.mail.yahoo.com",
                            MatchType = "Domain",
                            Pattern = "yahoo.co.uk",
                            Port = 993,
                            ProviderName = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("8f1bc95a-c068-1774-ece1-710e450c867b"),
                            Encryption = "SSL",
                            Host = "imap.mail.yahoo.com",
                            MatchType = "Domain",
                            Pattern = "yahoo.fr",
                            Port = 993,
                            ProviderName = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("6ff760cd-4874-f8f6-9185-e6aaa01ce0ce"),
                            Encryption = "SSL",
                            Host = "imap.mail.yahoo.com",
                            MatchType = "Domain",
                            Pattern = "yahoo.de",
                            Port = 993,
                            ProviderName = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("b54b68cf-6ebf-f888-6d5b-83b09d812b26"),
                            Encryption = "SSL",
                            Host = "imap.mail.yahoo.com",
                            MatchType = "Domain",
                            Pattern = "yahoo.nl",
                            Port = 993,
                            ProviderName = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("bf62f05f-8dca-89fb-36a5-06c2efc72bd1"),
                            Encryption = "SSL",
                            Host = "imap.mail.me.com",
                            MatchType = "Domain",
                            Pattern = "icloud.com",
                            Port = 993,
                            ProviderName = "iCloud"
                        },
                        new
                        {
                            Id = new Guid("17f02716-379a-cd5b-0b50-2db6a975bb03"),
                            Encryption = "SSL",
                            Host = "imap.mail.me.com",
                            MatchType = "Domain",
                            Pattern = "me.com",
                            Port = 993,
                            ProviderName = "iCloud"
                        },
                        new
                        {
                            Id = new Guid("f0fbac11-58fc-2369-55c5-c769138939fb"),
                            Encryption = "SSL",
                            Host = "imap.mail.me.com",
                            MatchType = "Domain",
                            Pattern = "mac.com",
                            Port = 993,
                            ProviderName = "iCloud"
                        },
                        new
                        {
                            Id = new Guid("0a4a4344-8a14-3b90-b717-0dec68e3f8e1"),
                            Encryption = "SSL",
                            Host = "imap.one.com",
                            MatchType = "Domain",
                            Pattern = "one.com",
                            Port = 993,
                            ProviderName = "one.com"
                        },
                        new
                        {
                            Id = new Guid("4d9d54fe-69ed-715e-f660-283fd2c2a7bf"),
                            Encryption = "SSL",
                            Host = "imap.zoho.com",
                            MatchType = "Domain",
                            Pattern = "zoho.com",
                            Port = 993,
                            ProviderName = "Zoho"
                        },
                        new
                        {
                            Id = new Guid("5de50aa5-b29d-05a1-4a0b-e1c14d3c8f2b"),
                            Encryption = "SSL",
                            Host = "imap.zoho.eu",
                            MatchType = "Domain",
                            Pattern = "zohomail.eu",
                            Port = 993,
                            ProviderName = "Zoho"
                        },
                        new
                        {
                            Id = new Guid("c69b93fb-5232-47ae-388a-99fe9024b9d2"),
                            Encryption = "SSL",
                            Host = "imap.fastmail.com",
                            MatchType = "Domain",
                            Pattern = "fastmail.com",
                            Port = 993,
                            ProviderName = "FastMail"
                        },
                        new
                        {
                            Id = new Guid("ae42cb34-55c2-b1c2-da7f-dd2b196efa44"),
                            Encryption = "STARTTLS",
                            Host = "127.0.0.1",
                            MatchType = "Domain",
                            Pattern = "protonmail.com",
                            Port = 1143,
                            ProviderName = "ProtonMail Bridge"
                        },
                        new
                        {
                            Id = new Guid("f5421ae2-6be2-dc13-c955-3a62d725920e"),
                            Encryption = "STARTTLS",
                            Host = "127.0.0.1",
                            MatchType = "Domain",
                            Pattern = "proton.me",
                            Port = 1143,
                            ProviderName = "ProtonMail Bridge"
                        },
                        new
                        {
                            Id = new Guid("e6981d4c-f118-4105-88b5-d07639931ff3"),
                            Encryption = "SSL",
                            Host = "imap.gmx.net",
                            MatchType = "Domain",
                            Pattern = "gmx.com",
                            Port = 993,
                            ProviderName = "GMX"
                        },
                        new
                        {
                            Id = new Guid("14b2d807-4b88-397c-b006-3f74fa32af45"),
                            Encryption = "SSL",
                            Host = "imap.gmx.net",
                            MatchType = "Domain",
                            Pattern = "gmx.de",
                            Port = 993,
                            ProviderName = "GMX"
                        },
                        new
                        {
                            Id = new Guid("224e8779-1908-9eae-31f7-e4d66fae6c5b"),
                            Encryption = "SSL",
                            Host = "imap.gmx.net",
                            MatchType = "Domain",
                            Pattern = "gmx.net",
                            Port = 993,
                            ProviderName = "GMX"
                        },
                        new
                        {
                            Id = new Guid("87b2a7bc-ce72-4ab8-5cd8-09a5bbb5a5c4"),
                            Encryption = "SSL",
                            Host = "imap.mail.de",
                            MatchType = "Domain",
                            Pattern = "mail.de",
                            Port = 993,
                            ProviderName = "Mail.de"
                        },
                        new
                        {
                            Id = new Guid("855630c8-45bd-eb28-26da-85c15bdb1c51"),
                            Encryption = "SSL",
                            Host = "imap.aol.com",
                            MatchType = "Domain",
                            Pattern = "aol.com",
                            Port = 993,
                            ProviderName = "AOL"
                        },
                        new
                        {
                            Id = new Guid("6bae2a0e-e388-4fec-b165-e9a7c20a7c8e"),
                            Encryption = "SSL",
                            Host = "secureimap.t-online.de",
                            MatchType = "Domain",
                            Pattern = "t-online.de",
                            Port = 993,
                            ProviderName = "T-Online"
                        },
                        new
                        {
                            Id = new Guid("9e17a8fb-ca3f-df13-9a3c-c94df6748aff"),
                            Encryption = "SSL",
                            Host = "imap.web.de",
                            MatchType = "Domain",
                            Pattern = "web.de",
                            Port = 993,
                            ProviderName = "Web.de"
                        },
                        new
                        {
                            Id = new Guid("6f3d34de-e7e5-f7cb-30fc-8ce4464c8dcf"),
                            Encryption = "SSL",
                            Host = "imap.telenet.be",
                            MatchType = "Domain",
                            Pattern = "telenet.be",
                            Port = 993,
                            ProviderName = "Telenet"
                        },
                        new
                        {
                            Id = new Guid("f07c9222-6d92-c435-868f-7e37be9cde10"),
                            Encryption = "SSL",
                            Host = "imap.ziggo.nl",
                            MatchType = "Domain",
                            Pattern = "ziggo.nl",
                            Port = 993,
                            ProviderName = "Ziggo"
                        },
                        new
                        {
                            Id = new Guid("09902a57-7f7b-5d7e-df3b-463dab159daf"),
                            Encryption = "SSL",
                            Host = "imap.kpnmail.nl",
                            MatchType = "Domain",
                            Pattern = "kpnmail.nl",
                            Port = 993,
                            ProviderName = "KPN"
                        },
                        new
                        {
                            Id = new Guid("a0f1ae43-1e97-5fd5-93d7-8f8d26276a03"),
                            Encryption = "SSL",
                            Host = "outlook.office365.com",
                            MatchType = "MxPattern",
                            Pattern = "protection.outlook.com",
                            Port = 993,
                            ProviderName = "Microsoft 365"
                        },
                        new
                        {
                            Id = new Guid("75e3c102-5e5c-b8ee-a555-385050fa19d1"),
                            Encryption = "SSL",
                            Host = "outlook.office365.com",
                            MatchType = "MxPattern",
                            Pattern = "outlook.com",
                            Port = 993,
                            ProviderName = "Microsoft 365"
                        },
                        new
                        {
                            Id = new Guid("dacacc40-6f81-7d95-b111-2d8247927d60"),
                            Encryption = "SSL",
                            Host = "imap.gmail.com",
                            MatchType = "MxPattern",
                            Pattern = "google.com",
                            Port = 993,
                            ProviderName = "Google Workspace"
                        },
                        new
                        {
                            Id = new Guid("cecb6a7e-3f78-9208-6c3c-5d2d87147164"),
                            Encryption = "SSL",
                            Host = "imap.gmail.com",
                            MatchType = "MxPattern",
                            Pattern = "googlemail.com",
                            Port = 993,
                            ProviderName = "Google Workspace"
                        },
                        new
                        {
                            Id = new Guid("52c2ff8b-7e49-c0c2-01d2-d02d0475ba84"),
                            Encryption = "SSL",
                            Host = "imap.mail.yahoo.com",
                            MatchType = "MxPattern",
                            Pattern = "yahoodns.net",
                            Port = 993,
                            ProviderName = "Yahoo"
                        },
                        new
                        {
                            Id = new Guid("28b2c5cb-7034-3343-18fa-5b883650f2c3"),
                            Encryption = "SSL",
                            Host = "imap.zoho.com",
                            MatchType = "MxPattern",
                            Pattern = "zoho.com",
                            Port = 993,
                            ProviderName = "Zoho"
                        },
                        new
                        {
                            Id = new Guid("9496877d-2676-81e1-81cd-1d24cc96e3f4"),
                            Encryption = "SSL",
                            Host = "imap.zoho.eu",
                            MatchType = "MxPattern",
                            Pattern = "zoho.eu",
                            Port = 993,
                            ProviderName = "Zoho"
                        },
                        new
                        {
                            Id = new Guid("286dc0ea-621d-aa0b-bf0d-c673ac25cf38"),
                            Encryption = "SSL",
                            Host = "imap.one.com",
                            MatchType = "MxPattern",
                            Pattern = "one.com",
                            Port = 993,
                            ProviderName = "one.com"
                        },
                        new
                        {
                            Id = new Guid("b13e9a8c-f273-f6f0-dbe1-92c7113b09b6"),
                            Encryption = "SSL",
                            Host = "imap.fastmail.com",
                            MatchType = "MxPattern",
                            Pattern = "fastmail.com",
                            Port = 993,
                            ProviderName = "FastMail"
                        });
                });

            modelBuilder.Entity("Migrify.Core.Entities.ImapSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EncryptedOAuthAccessToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EncryptedOAuthClientSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EncryptedOAuthRefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Encryption")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastTestedServerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("MigrationJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("OAuthClientId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OAuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("OAuthTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ResolvedIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId")
                        .IsUnique();

                    b.ToTable("ImapSettings");
                });

            modelBuilder.Entity("Migrify.Core.Entities.M365Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EncryptedClientSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("M365Settings");
                });

            modelBuilder.Entity("Migrify.Core.Entities.MigrationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentFolder")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("HasImapOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("MigrationMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("MigrationOptionsConfigured")
                        .HasColumnType("boolean");

                    b.Property<int>("ProcessedMessages")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SkipDuplicates")
                        .HasColumnType("boolean");

                    b.Property<int>("SkippedMessages")
                        .HasColumnType("integer");

                    b.Property<string>("SourceEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalMessages")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("MigrationJobs");
                });

            modelBuilder.Entity("Migrify.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SourceConnectorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Migrify.Core.Entities.DiscoveredMailbox", b =>
                {
                    b.HasOne("Migrify.Core.Entities.Project", "Project")
                        .WithMany("DiscoveredMailboxes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Migrify.Core.Entities.FolderMapping", b =>
                {
                    b.HasOne("Migrify.Core.Entities.MigrationJob", "MigrationJob")
                        .WithMany("FolderMappings")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("Migrify.Core.Entities.GoogleWorkspaceSettings", b =>
                {
                    b.HasOne("Migrify.Core.Entities.Project", "Project")
                        .WithOne("GoogleWorkspaceSettings")
                        .HasForeignKey("Migrify.Core.Entities.GoogleWorkspaceSettings", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Migrify.Core.Entities.ImapSettings", b =>
                {
                    b.HasOne("Migrify.Core.Entities.MigrationJob", "MigrationJob")
                        .WithOne("ImapSettings")
                        .HasForeignKey("Migrify.Core.Entities.ImapSettings", "MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("Migrify.Core.Entities.M365Settings", b =>
                {
                    b.HasOne("Migrify.Core.Entities.Project", "Project")
                        .WithOne("M365Settings")
                        .HasForeignKey("Migrify.Core.Entities.M365Settings", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Migrify.Core.Entities.MigrationJob", b =>
                {
                    b.HasOne("Migrify.Core.Entities.Project", "Project")
                        .WithMany("MigrationJobs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Migrify.Core.Entities.MigrationJob", b =>
                {
                    b.Navigation("FolderMappings");

                    b.Navigation("ImapSettings");
                });

            modelBuilder.Entity("Migrify.Core.Entities.Project", b =>
                {
                    b.Navigation("DiscoveredMailboxes");

                    b.Navigation("GoogleWorkspaceSettings");

                    b.Navigation("M365Settings");

                    b.Navigation("MigrationJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
